
###
POST http://localhost:8000/charts/wild
Content-Type: text/plain
Authorization: Basic dXNlcjpwYXNz

||: Ab | - | Fm | Db7 :||

###
GET http://localhost:8000/charts/wild

### 
POST http://localhost:8888/api/export
Content-Type: text/plain
X-API-Key: 1

title: Wild Thing
===
||: Ab | - | Fm6 | Gm7 :||